name: Publish docs via GitHub Pages
on:
  push:
    branches: [ 'main' ]
    paths: [ '.github/workflows/**', 'lib/**' ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true
jobs:
  build-pages:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: "./.nvmrc"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: "./package.json"
          run_install: |
            - recursive: true
              args: [--ignore-scripts, --frozen-lockfile]

      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Build Storybook
        run: |
          pnpm build:registry
          # Ensure the registry.json is generated before building shadcn components
          if [ ! -f registry.json ]; then
            echo "registry.json not found, exiting."
            exit 1
          fi
          # Build shadcn components and Storybook
          pnpm build:shadcn
          pnpm build:storybook

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "${{ github.workspace }}/storybook-static"
        continue-on-error: true

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
